/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Form;

import Clases.CallBack;
import Clases.Query;
import Entidad.Ingrediente;
import Tools.ExportToExcel;
import Tools.TextPrompt;
import java.awt.Color;
import java.awt.ScrollPane;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Arrays;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author DanielSantiago
 */
public class Form_Ingrediente extends javax.swing.JPanel {

    private boolean result;
    
    private String id;
    private String codigo;
    private String descrip;
    private String tipoingrediente;
    private String unidadmedida;
    private float preciounidad;
    private float rendimiento;
    private String proveedor;
    private String nota;
    
    private Query qry = new Query();
    /**
     * Creates new form Form_Ingrediente
     */
    public Form_Ingrediente() {
        initComponents();
        
        //ocultarColumna(tableIngrediente, 9);
        ocultarColumnas(tableIngrediente, Arrays.asList(0,3,6,9));
        //ocultarColumna(tableIngrediente, 6);
        //ocultarColumna(tableIngrediente, 9);
        
        fillIngrediente();
        
        //SeletedRowTable();
        //JScrollPane scrollPane = new JScrollPane(tableIngrediente);
        //btnGuardar.putClientProperty("JComponent.roundRect", true);
        //UIManager.setLookAndFeel(new FlatCarbonIJTheme());
        tableIngrediente.getTableHeader().setOpaque(false);
        tableIngrediente.getTableHeader().setBackground(new Color(0,71,171));
        tableIngrediente.getTableHeader().setForeground(Color.white);
        tableIngrediente.setRowHeight(25);
        //tableIngrediente.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        // Agregar la tabla a un JScrollPane
        JScrollPane scrollPane = new JScrollPane(tableIngrediente);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        tablePanel.add(scrollPane);
        
        //place holder de los TextField
        TextPrompt();
        
        //Ocultar campos 
        
        OcultarCampos();
        
        /*textProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent evt) {
                proveedor = textProveedor.getText();
                //System.out.println("Dato: " + proveedor);
                if (evt.getKeyCode() == KeyEvent.VK_F4) {
                    Form_Consultar formConsultar = new Form_Consultar(new CallBack() {
                        @Override
                        public void onDataReceived(List<String> data) {
                            //textTipoIngrediente.setText(data);
                            System.out.println(data);
                        }
                    },"Proveedor",Arrays.asList("sNombre",proveedor));
                    formConsultar.setVisible(true);
                    formConsultar.setLocationRelativeTo(null);
                    formConsultar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                }
            }
        });*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenuIngrediente = new javax.swing.JPopupMenu();
        editMenuTable = new javax.swing.JMenuItem();
        deleteMenuTable = new javax.swing.JMenuItem();
        tablePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableIngrediente = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        textCodigo = new javax.swing.JTextField();
        textDescrip = new javax.swing.JTextField();
        textNota = new javax.swing.JTextField();
        textPrecioUnidad = new javax.swing.JFormattedTextField();
        textRendimiento = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        textTipoIngredienteDescrip = new javax.swing.JTextField();
        textTipoIngrediente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        textProveedorDescrip = new javax.swing.JTextField();
        textProveedor = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        textUnidadMedida = new javax.swing.JTextField();
        textUnidadMedidaDescrip = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnExportExcel = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        idTextTipoIngrediente = new javax.swing.JTextField();
        idTextProveedor = new javax.swing.JTextField();
        idTextUnidadMedida = new javax.swing.JTextField();
        idTextIngrediente = new javax.swing.JTextField();

        popupMenuIngrediente.setBackground(new java.awt.Color(0, 71, 171));
        popupMenuIngrediente.setForeground(new java.awt.Color(255, 255, 255));

        editMenuTable.setBackground(new java.awt.Color(0, 71, 171));
        editMenuTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editMenuTable.setForeground(new java.awt.Color(255, 255, 255));
        editMenuTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/editar_24.png"))); // NOI18N
        editMenuTable.setText("Editar");
        editMenuTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMenuTableMouseClicked(evt);
            }
        });
        editMenuTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuTableActionPerformed(evt);
            }
        });
        popupMenuIngrediente.add(editMenuTable);

        deleteMenuTable.setBackground(new java.awt.Color(255, 102, 102));
        deleteMenuTable.setForeground(new java.awt.Color(255, 255, 255));
        deleteMenuTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar_2_24.png"))); // NOI18N
        deleteMenuTable.setText("Eliminar");
        deleteMenuTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMenuTableMouseClicked(evt);
            }
        });
        deleteMenuTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuTableActionPerformed(evt);
            }
        });
        popupMenuIngrediente.add(deleteMenuTable);

        setMinimumSize(new java.awt.Dimension(1050, 510));
        setPreferredSize(new java.awt.Dimension(1050, 510));
        setRequestFocusEnabled(false);

        tablePanel.setLayout(new java.awt.BorderLayout());

        tableIngrediente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableIngrediente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Código", "Descripción", "Id Tipo ingrediente", "Cod Tipo ingrediente", "Tipo ingrediente", "Id Unidad medida", "Cod Unidad medida", "Unidad medida", "Id Proveedor", "NIT ", "Proveedor", "Precio unidad", "Rendimiento", "Nota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableIngrediente.setAutoscrolls(false);
        tableIngrediente.setComponentPopupMenu(popupMenuIngrediente);
        tableIngrediente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableIngrediente.setFocusable(false);
        tableIngrediente.setOpaque(false);
        tableIngrediente.setRowHeight(25);
        tableIngrediente.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tableIngrediente.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tableIngrediente);

        tablePanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        textCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        textDescrip.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textDescrip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        textNota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textNota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        textPrecioUnidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        textPrecioUnidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        textPrecioUnidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        textRendimiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        textRendimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        textRendimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textTipoIngredienteDescrip.setBackground(new java.awt.Color(204, 204, 204));
        textTipoIngredienteDescrip.setText("Presionar F4");
        textTipoIngredienteDescrip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        textTipoIngredienteDescrip.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        textTipoIngredienteDescrip.setEnabled(false);
        jPanel3.add(textTipoIngredienteDescrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 270, 30));

        textTipoIngrediente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textTipoIngrediente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        textTipoIngrediente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textTipoIngredienteKeyPressed(evt);
            }
        });
        jPanel3.add(textTipoIngrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textProveedorDescrip.setBackground(new java.awt.Color(204, 204, 204));
        textProveedorDescrip.setText("Presionar F4");
        textProveedorDescrip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        textProveedorDescrip.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        textProveedorDescrip.setEnabled(false);
        jPanel2.add(textProveedorDescrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 260, 30));

        textProveedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        textProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textProveedorKeyPressed(evt);
            }
        });
        jPanel2.add(textProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textUnidadMedida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        textUnidadMedida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textUnidadMedidaKeyPressed(evt);
            }
        });
        jPanel4.add(textUnidadMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        textUnidadMedidaDescrip.setBackground(new java.awt.Color(204, 204, 204));
        textUnidadMedidaDescrip.setText("Presionar F4");
        textUnidadMedidaDescrip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        textUnidadMedidaDescrip.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        textUnidadMedidaDescrip.setEnabled(false);
        jPanel4.add(textUnidadMedidaDescrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 120, 30));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(textPrecioUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textRendimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNota)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textNota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPrecioUnidad)
                    .addComponent(textRendimiento)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setBackground(new java.awt.Color(102, 204, 0));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setDefaultCapable(false);
        btnGuardar.setFocusPainted(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(0, 71, 171));
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnExportExcel.setText("Exportar Excel");
        btnExportExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportExcelActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");

        idTextTipoIngrediente.setOpaque(true);

        idTextProveedor.setOpaque(true);

        idTextIngrediente.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idTextIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTextTipoIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTextProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTextUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 346, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExportExcel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExportExcel)
                        .addComponent(jButton4)
                        .addComponent(idTextTipoIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idTextProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idTextUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idTextIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fillIngrediente(){
        try {
            //List<Ingrediente> ingredientes = qry.ObtenerRegistros("Ingrediente", Ingrediente.rowMapper());
            List<Map<String, Object>> registros = qry.ObtenerRegistrosIngredientes("Ingrediente");
            //System.out.println("Nuevo metodo para obtener registros: " + registros);
            DefaultTableModel tableModel = (DefaultTableModel) tableIngrediente.getModel();
            tableModel.setRowCount(0);
            for (Map<String, Object> registro : registros) {
                tableModel.addRow(new Object[]{
                    registro.get("iIngrediente"),         // ID del ingrediente
                    registro.get("ingredienteCodigo"),   // Código del ingrediente
                    registro.get("ingredienteDescrip"),  // Descripción del ingrediente
                    registro.get("tipoId"),
                    registro.get("tipoCodigo"),          // Código del tipo de ingrediente
                    registro.get("tipoNombre"),          // Nombre del tipo de ingrediente
                    registro.get("medidaId"),        // Id de la medida
                    registro.get("medidaCodigo"),        // Código de la medida
                    registro.get("medidaNombre"),        // Nombre de la medida
                    registro.get("proveedorId"),        // NIT del proveedor
                    registro.get("proveedorNit"),        // NIT del proveedor
                    registro.get("proveedorNombre"),     // Nombre del proveedor
                    registro.get("ingredientePrecio"),   // Precio del ingrediente
                    registro.get("ingredienteRendimiento"), // Rendimiento del ingrediente
                    registro.get("ingredienteNota")      // Nota del ingrediente
                });
            }
            /*for (Ingrediente ingrediente : ingredientes) {
                tableModel.addRow(new Object[]{
                    ingrediente.getIngrediente(),
                    ingrediente.getCodigo(),
                    ingrediente.getDescrip(),
                    ingrediente.getTipoingrediente(),
                    ingrediente.getMedida(),
                    ingrediente.getProveedor(),
                    ingrediente.getPreciounidad(),
                    ingrediente.getRendimiento(),
                    ingrediente.getNota(),
                    ingrediente.isInactivo()
                });
            }*/
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    
    // Método para ocultar una columna por índice
    public static void ocultarColumna(JTable table, int columnIndex) {
        TableColumn columna = table.getColumnModel().getColumn(columnIndex);
        table.getColumnModel().removeColumn(columna);
    }
    
    // Método para ocultar varias columnas usando una lista
    public static void ocultarColumnas(JTable table, List<Integer> columnIndices) {
        // Ordenar los índices en orden descendente para evitar problemas al eliminar columnas
        Collections.sort(columnIndices, Collections.reverseOrder());
        for (int columnIndex : columnIndices) {
            ocultarColumna(table, columnIndex);
        }
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        id = idTextIngrediente.getText();
        codigo = textCodigo.getText();
        descrip = textDescrip.getText();
        tipoingrediente = idTextTipoIngrediente.getText();
        unidadmedida = idTextUnidadMedida.getText();
        preciounidad = Float.parseFloat(textPrecioUnidad.getText());
        rendimiento = Float.parseFloat(textRendimiento.getText());
        proveedor = idTextProveedor.getText();
        nota = textNota.getText();
        
        if(!"".equals(id)){
            try {
                Map<String, Object> columnValues = new HashMap<>();
                columnValues.put("iTipoIngrediente", tipoingrediente);
                columnValues.put("iMedida", unidadmedida);
                columnValues.put("iProveedor", proveedor);
                columnValues.put("sCodigo", codigo);
                columnValues.put("sDescrip", descrip);
                columnValues.put("yPrecio", preciounidad);
                columnValues.put("rRendimiento", rendimiento);
                columnValues.put("mNota", nota);
                columnValues.put("bInactivo", false);
                columnValues.put("iIngrediente", id);

                result = qry.ActualizarRegistros("Ingrediente", columnValues, "iIngrediente");
                LimpiarCampos();
                fillIngrediente();
                if (result){
                    JOptionPane.showMessageDialog(null, "Registro actualizado correctamente");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al actualizar");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            

            try {
                Map<String, Object> columnValues = new HashMap<>();
                columnValues.put("iTipoIngrediente", tipoingrediente);
                columnValues.put("iMedida", unidadmedida);
                columnValues.put("iProveedor", proveedor);
                columnValues.put("sCodigo", codigo);
                columnValues.put("sDescrip", descrip);
                columnValues.put("yPrecio", preciounidad);
                columnValues.put("rRendimiento", rendimiento);
                columnValues.put("mNota", nota);
                columnValues.put("bInactivo", false);

                result = qry.InsertarRegistro("Ingrediente", columnValues);
                LimpiarCampos();
                fillIngrediente();
                if (result){
                    JOptionPane.showMessageDialog(null, "Registro guardado correctamente");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al guardar");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void editMenuTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuTableActionPerformed
        
        // Obtener la fila seleccionada
        int filaSeleccionada = tableIngrediente.getSelectedRow();

        // Verificar que haya una fila seleccionada
        if (filaSeleccionada != -1) {
            // Convertir el índice de la fila seleccionada al índice del modelo de datos
            int filaModelo = tableIngrediente.convertRowIndexToModel(filaSeleccionada);

            idTextIngrediente.setText(tableIngrediente.getModel().getValueAt(filaModelo, 0).toString());
            textCodigo.setText(tableIngrediente.getModel().getValueAt(filaModelo, 1).toString());
            textDescrip.setText(tableIngrediente.getModel().getValueAt(filaModelo, 2).toString());
            idTextTipoIngrediente.setText(tableIngrediente.getModel().getValueAt(filaModelo, 3).toString());
            textTipoIngrediente.setText(tableIngrediente.getModel().getValueAt(filaModelo, 4).toString());
            textTipoIngredienteDescrip.setText(tableIngrediente.getModel().getValueAt(filaModelo, 5).toString());
            idTextUnidadMedida.setText(tableIngrediente.getModel().getValueAt(filaModelo, 6).toString());
            textUnidadMedida.setText(tableIngrediente.getModel().getValueAt(filaModelo, 7).toString());
            textUnidadMedidaDescrip.setText(tableIngrediente.getModel().getValueAt(filaModelo, 8).toString());
            idTextProveedor.setText(tableIngrediente.getModel().getValueAt(filaModelo, 9).toString());
            textProveedor.setText(tableIngrediente.getModel().getValueAt(filaModelo, 10).toString());
            textProveedorDescrip.setText(tableIngrediente.getModel().getValueAt(filaModelo, 11).toString());
            textPrecioUnidad.setText(tableIngrediente.getModel().getValueAt(filaModelo, 12).toString());
            textRendimiento.setText(tableIngrediente.getModel().getValueAt(filaModelo, 13).toString());
            textNota.setText(tableIngrediente.getModel().getValueAt(filaModelo, 14).toString());

            // Obtener los datos directamente del modelo de datos
            //String id = tableIngrediente.getModel().getValueAt(filaModelo, 0).toString(); // Índice en el modelo
            //String nombre = tableIngrediente.getModel().getValueAt(filaModelo, 1).toString();
            //String apellido = tableIngrediente.getModel().getValueAt(filaModelo, 2).toString();

            // Mostrar los datos en la consola o en un JOptionPane
            //System.out.println("ID: " + id + ", Nombre: " + nombre + ", Apellido: " + apellido);
            //JOptionPane.showMessageDialog(null, "ID: " + id + "\nNombre: " + nombre + "\nApellido: " + apellido);
        }
    }//GEN-LAST:event_editMenuTableActionPerformed

    private void textProveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textProveedorKeyPressed
        proveedor = textProveedor.getText();
        if (evt.getKeyCode() == KeyEvent.VK_F4) {
            Form_Consultar formConsultar = new Form_Consultar(new CallBack() {
                @Override
                public void onDataReceived(List<String> data) {
                    //textTipoIngrediente.setText(data);
                    //System.out.println(data);
                    idTextProveedor.setText(data.get(0));
                    textProveedor.setText(data.get(1));
                    textProveedorDescrip.setText(data.get(2));
                }
            },"Proveedor",Arrays.asList("sNombre",proveedor));
            formConsultar.setVisible(true);
            formConsultar.setLocationRelativeTo(null);
            formConsultar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_textProveedorKeyPressed

    private void textTipoIngredienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTipoIngredienteKeyPressed
        tipoingrediente = textTipoIngrediente.getText();
        if (evt.getKeyCode() == KeyEvent.VK_F4) {
            Form_Consultar formConsultar = new Form_Consultar(new CallBack() {
                @Override
                public void onDataReceived(List<String> data) {
                    //textTipoIngrediente.setText(data);
                    //System.out.println(data);
                    idTextTipoIngrediente.setText(data.get(0));
                    textTipoIngrediente.setText(data.get(1));
                    textTipoIngredienteDescrip.setText(data.get(2));
                }
            },"TipoIngrediente",Arrays.asList("sNombre",tipoingrediente));
            formConsultar.setVisible(true);
            formConsultar.setLocationRelativeTo(null);
            formConsultar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_textTipoIngredienteKeyPressed

    private void textUnidadMedidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textUnidadMedidaKeyPressed
        unidadmedida = textUnidadMedida.getText();
        if (evt.getKeyCode() == KeyEvent.VK_F4) {
            Form_Consultar formConsultar = new Form_Consultar(new CallBack() {
                @Override
                public void onDataReceived(List<String> data) {
                    //textTipoIngrediente.setText(data);
                    //System.out.println(data);
                    idTextUnidadMedida.setText(data.get(0));
                    textUnidadMedida.setText(data.get(1));
                    textUnidadMedidaDescrip.setText(data.get(2));
                }
            },"Medida",Arrays.asList("sNombre",unidadmedida));
            formConsultar.setVisible(true);
            formConsultar.setLocationRelativeTo(null);
            formConsultar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_textUnidadMedidaKeyPressed

    private void editMenuTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMenuTableMouseClicked
        
    }//GEN-LAST:event_editMenuTableMouseClicked

    private void btnExportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportExcelActionPerformed
        ExportToExcel obj;

        try {
            obj = new ExportToExcel();
            obj.exportarExcel(tableIngrediente);
        } catch (IOException ex) {
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_btnExportExcelActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        LimpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void deleteMenuTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMenuTableMouseClicked
        
        
    }//GEN-LAST:event_deleteMenuTableMouseClicked

    private void deleteMenuTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuTableActionPerformed
        //JOptionPane.showMessageDialog(null, "Error al eliminar el registro.");
        // Obtener la fila seleccionada
        int filaSeleccionada = tableIngrediente.getSelectedRow();

        // Verificar que haya una fila seleccionada
        if (filaSeleccionada != -1) {
            int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de eliminar el registro?",
                "Confirmar Eliminación",
                JOptionPane.YES_NO_OPTION
            );

            if (confirmacion == JOptionPane.YES_OPTION) {
                // Convertir el índice de la fila seleccionada al índice del modelo de datos
                int filaModelo = tableIngrediente.convertRowIndexToModel(filaSeleccionada);

                idTextIngrediente.setText(tableIngrediente.getModel().getValueAt(filaModelo, 0).toString());

                try {
                    // Validar ID del ingrediente
                    int idIngrediente = Integer.parseInt(idTextIngrediente.getText());

                    // Eliminar registro
                    result = qry.EliminarRegistroPorId("Ingrediente", "iIngrediente", idIngrediente);

                    if (result) {
                        JOptionPane.showMessageDialog(null, "Registro eliminado correctamente");
                        LimpiarCampos();
                        fillIngrediente();
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al eliminar el registro.");
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "El ID del ingrediente no es válido.", "Error", JOptionPane.ERROR_MESSAGE);
                } catch (SQLException ex) {
                    Logger.getLogger(Form_Ingrediente.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Error al eliminar el registro: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una fila para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteMenuTableActionPerformed

    public void onDataReceived(List<String> data){
        System.out.println(data);
    }
        
    private void SeletedRowTable() {
        tableIngrediente.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // Obtener la fila seleccionada
                int filaSeleccionada = tableIngrediente.getSelectedRow();

                // Verificar que haya una fila seleccionada
                if (filaSeleccionada != -1) {
                    // Convertir el índice de la fila seleccionada al índice del modelo de datos
                    int filaModelo = tableIngrediente.convertRowIndexToModel(filaSeleccionada);

                    // Obtener los datos directamente del modelo de datos
                    String id = tableIngrediente.getModel().getValueAt(filaModelo, 0).toString(); // Índice en el modelo
                    String nombre = tableIngrediente.getModel().getValueAt(filaModelo, 1).toString();
                    String apellido = tableIngrediente.getModel().getValueAt(filaModelo, 2).toString();

                    // Mostrar los datos en la consola o en un JOptionPane
                    System.out.println("ID: " + id + ", Nombre: " + nombre + ", Apellido: " + apellido);
                    JOptionPane.showMessageDialog(null, "ID: " + id + "\nNombre: " + nombre + "\nApellido: " + apellido);
                }
            }
        });
    }

    public void LimpiarCampos(){
        idTextIngrediente.setText("");
        idTextTipoIngrediente.setText(""); 
        idTextProveedor.setText("");
        idTextUnidadMedida.setText("");
        textUnidadMedida.setText("");
        textUnidadMedidaDescrip.setText("");
        textCodigo.setText("");
        textDescrip.setText("");
        textNota.setText("");
        textPrecioUnidad.setText("");
        textRendimiento.setText("");
        textProveedor.setText("");
        textProveedorDescrip.setText("");
        textTipoIngrediente.setText("");
        textTipoIngredienteDescrip.setText("");
    }
    
    private void OcultarCampos(){
        idTextIngrediente.setVisible(false);
        idTextUnidadMedida.setVisible(false);
        idTextProveedor.setVisible(false);
        idTextTipoIngrediente.setVisible(false);
    }
    
    private void TextPrompt(){
        TextPrompt textcodigo = new TextPrompt("Codigo", textCodigo, Color.black);
        TextPrompt textdescrip = new TextPrompt("Descripción", textDescrip, Color.black);
        TextPrompt texttipoingrediente = new TextPrompt("Tipo de ingrediente", textTipoIngrediente, Color.black);
        TextPrompt textunidadmedida = new TextPrompt("Unidad de medida", textUnidadMedida, Color.black);
        TextPrompt textpreciounidad = new TextPrompt("Precio unidad", textPrecioUnidad, Color.black);
        TextPrompt textrendimiento = new TextPrompt("Redimiento(%)", textRendimiento, Color.black);
        TextPrompt textproveedor = new TextPrompt("Proveedor", textProveedor, Color.black);
        TextPrompt textnota = new TextPrompt("Nota", textNota, Color.black);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportExcel;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JMenuItem deleteMenuTable;
    private javax.swing.JMenuItem editMenuTable;
    private javax.swing.JTextField idTextIngrediente;
    private javax.swing.JTextField idTextProveedor;
    private javax.swing.JTextField idTextTipoIngrediente;
    private javax.swing.JTextField idTextUnidadMedida;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu popupMenuIngrediente;
    private javax.swing.JTable tableIngrediente;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextField textDescrip;
    private javax.swing.JTextField textNota;
    private javax.swing.JFormattedTextField textPrecioUnidad;
    private javax.swing.JTextField textProveedor;
    private javax.swing.JTextField textProveedorDescrip;
    private javax.swing.JFormattedTextField textRendimiento;
    private javax.swing.JTextField textTipoIngrediente;
    private javax.swing.JTextField textTipoIngredienteDescrip;
    private javax.swing.JTextField textUnidadMedida;
    private javax.swing.JTextField textUnidadMedidaDescrip;
    // End of variables declaration//GEN-END:variables

}
