/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Form;

import Clases.Query;
import Entidad.Ingrediente;
import Tools.TextPrompt;
import java.awt.Color;
import java.awt.ScrollPane;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DanielSantiago
 */
public class Form_Ingrediente extends javax.swing.JPanel {

    private boolean result;
    
    private String codigo;
    private String descrip;
    private String tipoingrediente;
    private String unidadmedida;
    private float preciounidad;
    private float rendimiento;
    private String proveedor;
    private String nota;
    
    private Query qry = new Query();
    /**
     * Creates new form Form_Ingrediente
     */
    public Form_Ingrediente() {
        initComponents();
        fillIngrediente();
        //JScrollPane scrollPane = new JScrollPane(tableIngrediente);
        //btnGuardar.putClientProperty("JComponent.roundRect", true);
        //UIManager.setLookAndFeel(new FlatCarbonIJTheme());
        tableIngrediente.getTableHeader().setOpaque(false);
        tableIngrediente.getTableHeader().setBackground(new Color(0,71,171));
        tableIngrediente.getTableHeader().setForeground(Color.white);
        tableIngrediente.setRowHeight(25);
        
        TextPrompt textcodigo = new TextPrompt("Codigo", textCodigo, Color.black);
        TextPrompt textdescrip = new TextPrompt("Descripción", textDescrip, Color.black);
        TextPrompt texttipoingrediente = new TextPrompt("Tipo de ingrediente", textTipoIngrediente, Color.black);
        TextPrompt textunidadmedida = new TextPrompt("Unidad de medida", textUnidadMedida, Color.black);
        TextPrompt textpreciounidad = new TextPrompt("Precio unidad", textPrecioUnidad, Color.black);
        TextPrompt textrendimiento = new TextPrompt("Redimiento(%)", textRendimiento, Color.black);
        TextPrompt textproveedor = new TextPrompt("Proveedor", textProveedor, Color.black);
        TextPrompt textnota = new TextPrompt("Nota", textNota, Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenuIngrediente = new javax.swing.JPopupMenu();
        editMenuTable = new javax.swing.JMenuItem();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableIngrediente = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        textCodigo = new javax.swing.JTextField();
        textDescrip = new javax.swing.JTextField();
        textTipoIngrediente = new javax.swing.JTextField();
        textUnidadMedida = new javax.swing.JTextField();
        textProveedor = new javax.swing.JTextField();
        textNota = new javax.swing.JTextField();
        textPrecioUnidad = new javax.swing.JFormattedTextField();
        textRendimiento = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        editMenuTable.setText("jMenuItem3");
        popupMenuIngrediente.add(editMenuTable);

        setMinimumSize(new java.awt.Dimension(1050, 510));
        setPreferredSize(new java.awt.Dimension(1050, 510));
        setRequestFocusEnabled(false);

        tableIngrediente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableIngrediente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Tipo ingrediente", "Unidad medida", "Proveedor", "Precio unidad", "Rendimiento", "Nota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableIngrediente.setComponentPopupMenu(popupMenuIngrediente);
        tableIngrediente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableIngrediente.setFocusable(false);
        tableIngrediente.setOpaque(false);
        tableIngrediente.setRowHeight(25);
        tableIngrediente.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tableIngrediente.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tableIngrediente);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );

        textCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        textDescrip.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textDescrip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        textTipoIngrediente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textTipoIngrediente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        textUnidadMedida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textUnidadMedida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        textProveedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        textNota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textNota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        textPrecioUnidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        textPrecioUnidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        textPrecioUnidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        textRendimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        textRendimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(textPrecioUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textRendimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNota))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textTipoIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTipoIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textNota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textPrecioUnidad)
                    .addComponent(textRendimiento))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        btnGuardar.setBackground(new java.awt.Color(0, 71, 171));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setDefaultCapable(false);
        btnGuardar.setFocusPainted(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(720, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3)
                        .addComponent(jButton4)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fillIngrediente(){
        try {
            List<Ingrediente> ingredientes = qry.ObtenerRegistros("Ingrediente", Ingrediente.rowMapper());
            DefaultTableModel tableModel = (DefaultTableModel) tableIngrediente.getModel();
            tableModel.setRowCount(0);
            for (Ingrediente ingrediente : ingredientes) {
                tableModel.addRow(new Object[]{
                    ingrediente.getCodigo(),
                    ingrediente.getDescrip(),
                    ingrediente.getTipoingrediente(),
                    ingrediente.getMedida(),
                    ingrediente.getProveedor(),
                    ingrediente.getPreciounidad(),
                    ingrediente.getRendimiento(),
                    ingrediente.getNota(),
                    ingrediente.isInactivo()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        codigo = textCodigo.getText();
        descrip = textDescrip.getText();
        tipoingrediente = textTipoIngrediente.getText();
        unidadmedida = textUnidadMedida.getText();
        preciounidad = Float.parseFloat(textPrecioUnidad.getText());
        rendimiento = Float.parseFloat(textRendimiento.getText());
        proveedor = textProveedor.getText();
        nota = textNota.getText();
        
        try {
            Map<String, Object> columnValues = new HashMap<>();
            columnValues.put("iTipoIngrediente", 3);
            columnValues.put("iMedida", 3);
            columnValues.put("iProveedor", 1);
            columnValues.put("sCodigo", codigo);
            columnValues.put("sDescrip", descrip);
            columnValues.put("yPrecio", preciounidad);
            columnValues.put("rRendimiento", rendimiento);
            columnValues.put("mNota", nota);
            columnValues.put("bInactivo", false);

            result = qry.InsertarRegistro("Ingrediente", columnValues);
            if (result){
                JOptionPane.showMessageDialog(null, "Registro guardado correctamente");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JMenuItem editMenuTable;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu popupMenuIngrediente;
    private javax.swing.JTable tableIngrediente;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextField textDescrip;
    private javax.swing.JTextField textNota;
    private javax.swing.JFormattedTextField textPrecioUnidad;
    private javax.swing.JTextField textProveedor;
    private javax.swing.JFormattedTextField textRendimiento;
    private javax.swing.JTextField textTipoIngrediente;
    private javax.swing.JTextField textUnidadMedida;
    // End of variables declaration//GEN-END:variables
}
